### ISSUE TITLE
Example repo for development of an actual new spec

### ISSUE THREAD

**Issue by sserichpersonal** [CommunitySpecification/1.0#4]
First of all a thank-you to Justin Colannino for pointing me to this project.

I'm still a bit new to advanced GitHub features, so I was sure whether this would merit a new Issue or an Action or a discussion topic in some other forum. So I'll take a shot here first. Feel free to close it if it doesn't belong here.

I'm interested in possibly proposing to my current employer (Open Geospatial Consortium) that we consider trying out the Community Spec in practice. The 1.0 spec could potentially take away a lot of the worry and reinvention that might have otherwise been needed (thanks for this!).

But now I'd like to gain at least a notional understanding of what might take place in the subsequent spec development to create an actual technical specification. It seems to me that perhaps GitHub might be well-suited for carrying out that work as well... maybe even all the way through to source code development and deployment for reference implementations.

Are you aware whether anybody given any thought to this yet? If not, that's fine. I just didn't want to start reinventing any of these wheels either.

Thanks.

**Comment by sethnewberry** [comment]
Scott, We created the Community Specification out of the efforts of the Joint Development Foundation (an affiliate of the Linux Foundation) as a simple way to create a collaboration where the governance and process is entirely contained within a repository.  The governance and process is sufficient to create a specification that would meet most SDO's definition of an Open Specification.  The Community Spec is consistent with the JDF Specification process and so can be scaled up if the early efforts of the community warrant creating a more organized effort, or if funding or holding of common assets becomes a requirement.  You may also simply pull the repo into your OGC organization as a tool you would use internally.  If you go to the jointdevelopment dot org website and reach out through the admin email, I would be happy to talk with you further.

**Comment by sserichpersonal** [comment]
Excellent. Yes, Justin recommended the JDF as well. Let's close this one and carry on the conversation over there. Thanks Seth.

**Comment by nicorikken** [comment]
@sethnewberry is the example repo already public? I checked https://github.com/Joint-Development-Foundation but didn't see it. My current interest is into GitHub issue/PR templates to aid in the change request process.
