### ISSUE TITLE
Consider noting Community-Spec-1.0 license identifier in repo

### ISSUE THREAD

**Issue by swinslow** [CommunitySpecification/1.0#6]
In the SPDX License List v3.15 release this past weekend, the Community Specification License was added with the identifier `Community-Spec-1.0`:

https://spdx.org/licenses/Community-Spec-1.0.html

Is that something that would be worth noting in this repo, perhaps in the README file?

**Comment by mkdolan** [comment]
Yes, we should do that.

**Comment by jpradocueva** [comment]
PR #16  was merged.
